"use strict";

const menuButton = document.querySelector(".menu-toggle");
const navigation = document.querySelector(".site-nav");
const navigationLinks = document.querySelectorAll(".site-nav a");
const year = document.querySelector("#current-year");
const languageButtons = document.querySelectorAll(".language-button");

const translations = {
  en: {
    pageTitle: "Boris Ramirez | Portfolio", description: "Boris Ramirez's portfolio, experience, projects, and technical skills.", logoLabel: "Go to homepage", menuToggle: "Toggle navigation", languageLabel: "Select language", profilePhotoAlt: "Portrait of Boris Ramirez",
    navAbout: "About", navExperience: "Experience", navProjects: "Projects", navSkills: "Skills", navHobbies: "Hobbies",
    heroGreeting: "Hello, I'm", heroTitle: "Cloud & DevOps Enthusiast", heroCopy: "I believe every stage of life is an opportunity to learn, grow, and begin again. Today, I choose to move forward with curiosity, turn challenges into experience, and build a path with purpose and balance.", viewWork: "View my work", moreAbout: "More about me",
    aboutLabel: "About me", aboutTitle: "Building a new chapter", aboutLead: "I am a curious and persistent person with a constant need to learn. Throughout my professional life, I have faced different challenges, technologies, and stages that have taught me that growth often means daring to begin again.\n\nToday, I am living through one of those stages. After years of experience in technology and infrastructure, I decided to focus my path on Cloud and DevOps, return to studying, build projects from scratch, and challenge myself with new things.\n\nOutside technology, I also value the simple things: spending time with family and friends, enjoying my time, staying active, and continuing to learn. I want to grow professionally, but also to enjoy the process and build a life with purpose and balance.\n\nThis portfolio is a small part of that moment: a place where I can show what I have done, what I am learning, and, above all, where I want to go next.", aboutCopy: "",
    experienceLabel: "Work experience", experienceTitle: "Where I've contributed", present: "Present", cloudExperienceTitle: "Building practical cloud experience", cloudExperienceSubtitle: "Independent learning & projects", cloudExperienceCopy: "Designing and configuring AWS infrastructure while documenting decisions around access, security, deployment, and web hosting.", yourDates: "May 2020 – Jul 2026", yourRole: "Infrastructure and Platform Engineer", companyName: "CoasinLogicalis", experiencePlaceholder: "Administration and Level 2 support of critical infrastructure for enterprise and telecommunications customers across Latin America, working with Linux, VMware, Cisco UCS, and monitoring platforms. Responsible for investigating and resolving complex production incidents, collaborating with customers, engineering teams, and technology vendors to support service availability, stability, and operational continuity.",
    experienceThreeDates: "Jul 2018 – May 2020", experienceThreeRole: "Systems Engineer", experienceThreeCompany: "LOGICALIS", experienceThreeCopy: "Support and administration of the Banco Itaú SuperAPP infrastructure across Development, QA, and Production environments, managing 42 RHEL servers and using Puppet Enterprise and Red Hat Satellite for deployments, configuration, and patching. Incident resolution, SSL/TLS certificate administration, and monitoring with Splunk Enterprise to support platform stability and continuity.",
    experienceFourDates: "Mar 2014 – Jul 2018", experienceFourRole: "Deployment Support Specialist", experienceFourCompany: "NOKIA", experienceFourCopy: "Supported the deployment and production readiness of new Nokia AOR platform releases for Telefónica Chile in RHEL environments. Performed IOT/UAT testing, troubleshooting, patch validation, and collaboration with Nokia Spain engineering teams to resolve defects. Developed Bash scripts to automate testing activities.",
    experienceFiveDates: "Apr 2013 – Oct 2013", experienceFiveRole: "Software Developer (Freelance)", experienceFiveCompany: "SRB CORP S.A.", experienceFiveCopy: "Developed new features for Sacyr Chile's web-based ERP system, contributing to requirements gathering and the design and implementation of solutions using PHP, JavaScript, HTML, CSS, and MySQL. Performed functional testing, generated Excel reports, and prepared technical documentation for delivery to the customer.",
    experienceSixDates: "Mar 2011 – Apr 2013", experienceSixRole: "Software Developer", experienceSixCompany: "SIGTEC LTDA.", experienceSixCopy: "Developed and maintained the AITUE web ERP for customers across different industries, contributing to requirements analysis and the design and implementation of features using PHP, JavaScript, HTML, CSS, and MySQL. Modified databases, resolved defects, performed functional testing, supported customers, and prepared technical documentation.",
    projectsLabel: "Projects", projectsTitle: "Things I'm building", projectOneTitle: "Personal Portfolio Infrastructure", projectOneCopy: "A portfolio hosted on Amazon EC2 with Route 53 DNS, Nginx, an Elastic IP, and secure administration through AWS Systems Manager Session Manager.", viewRepository: "View on GitHub", projectTwoTitle: "This Portfolio Website", projectTwoCopy: "A responsive, accessible personal site built with semantic HTML, modern CSS, and lightweight JavaScript—without a framework.", nextProject: "Next project", nextProjectCopy: "This space is ready for the next challenge, experiment, or useful tool I build.", comingSoon: "Coming soon",
    skillsLabel: "Skills", skillsTitle: "Tools and technologies", cloud: "AWS Services", cloudList: "Amazon EC2, Route 53, Systems Manager, IAM, Elastic IP", systems: "Systems & Infrastructure", systemsList: "Linux (RHEL), Nginx, SSH, DNS, TLS/HTTPS, VMware, Cisco UCS", development: "Development & Automation", developmentList: "HTML, CSS, JavaScript, PHP, MySQL, Bash, Git, GitHub", practices: "Operations & Practices", practicesList: "Monitoring, troubleshooting, deployments, patching, documentation, security fundamentals",
    hobbiesLabel: "Outside of work", hobbiesTitle: "Hobbies and interests", hobbiesCopy: "Outside of work, I enjoy the simple things that help me maintain balance: spending time with my son and my partner, traveling and discovering new places, exercising, and playing football. I also enjoy a good movie, reading, and dedicating time to one of my most creative hobbies: drawing my own manga.", technology: "Technology", continuousLearning: "Continuous learning", personalProjects: "Personal projects", familyTime: "Family time", travel: "Travel", sportsAndFootball: "Sports & football", movies: "Movies", reading: "Reading", drawingManga: "Drawing manga", builtBy: "Designed and built by Boris Ramirez.", rights: "All rights reserved."
  },
  es: {
    pageTitle: "Boris Ramirez | Portafolio", description: "Portafolio, experiencia, proyectos y habilidades técnicas de Boris Ramirez.", logoLabel: "Ir al inicio", menuToggle: "Abrir o cerrar navegación", languageLabel: "Seleccionar idioma", profilePhotoAlt: "Retrato de Boris Ramirez",
    navAbout: "Sobre mí", navExperience: "Experiencia", navProjects: "Proyectos", navSkills: "Habilidades", navHobbies: "Pasatiempos",
    heroGreeting: "Hola, soy", heroTitle: "Entusiasta de Cloud y DevOps", heroCopy: "Creo que cada etapa de la vida es una oportunidad para aprender, crecer y volver a comenzar. Hoy elijo avanzar con curiosidad, transformar los desafíos en experiencia y construir un camino con propósito y equilibrio.", viewWork: "Ver mi trabajo", moreAbout: "Más sobre mí",
    aboutLabel: "Sobre mí", aboutTitle: "Construyendo una nueva etapa", aboutLead: "Soy una persona curiosa, perseverante y con una necesidad constante de aprender. A lo largo de mi vida profesional he pasado por distintos desafíos, tecnologías y etapas que me han enseñado que crecer muchas veces significa atreverse a comenzar de nuevo.\n\nHoy estoy viviendo una de esas etapas. Después de años de experiencia en tecnología e infraestructura, decidí orientar mi camino hacia Cloud y DevOps, volver a estudiar, construir proyectos desde cero y desafiarme con cosas nuevas.\n\nFuera de la tecnología, también valoro las cosas simples: compartir con mi familia y amigos, disfrutar mi tiempo, mantenerme activo y seguir aprendiendo. Busco crecer profesionalmente, pero también disfrutar el proceso y construir una vida con propósito y equilibrio.\n\nEste portafolio es una pequeña parte de ese momento: un lugar donde puedo mostrar lo que he hecho, lo que estoy aprendiendo y, sobre todo, hacia dónde quiero seguir avanzando.", aboutCopy: "",
    experienceLabel: "Experiencia laboral", experienceTitle: "Dónde he contribuido", present: "Actualidad", cloudExperienceTitle: "Desarrollo de experiencia práctica en cloud", cloudExperienceSubtitle: "Aprendizaje independiente y proyectos", cloudExperienceCopy: "Diseño y configuración de infraestructura AWS, documentando decisiones sobre acceso, seguridad, despliegue y alojamiento web.", yourDates: "May 2020 – Jul 2026", yourRole: "Ingeniero de Infraestructura y Plataformas", companyName: "CoasinLogicalis", experiencePlaceholder: "Administración y soporte de infraestructura crítica de Nivel 2 para clientes empresariales y de telecomunicaciones en Latinoamérica, trabajando con Linux, VMware, Cisco UCS y plataformas de monitoreo. Responsable de investigar y resolver incidentes complejos en producción, colaborando con clientes, equipos de ingeniería y fabricantes tecnológicos para contribuir a la disponibilidad, estabilidad y continuidad operacional de los servicios.",
    experienceThreeDates: "Jul 2018 – May 2020", experienceThreeRole: "Ingeniero de Sistemas ", experienceThreeCompany: "LOGICALIS", experienceThreeCopy: "Soporte y administración de la infraestructura de Banco Itaú SuperAPP en ambientes de Desarrollo, QA y Producción, gestionando 42 servidores RHEL y utilizando Puppet Enterprise y Red Hat Satellite para despliegues, configuración y parchado. Resolución de incidentes, administración de certificados SSL/TLS y monitoreo con Splunk Enterprise para contribuir a la estabilidad y continuidad de la plataforma.",
    experienceFourDates: "Mar 2014 – Jul 2018", experienceFourRole: "Especialista de Soporte para Despliegues ", experienceFourCompany: "NOKIA", experienceFourCopy: "Soporte al despliegue y preparación para producción de nuevas versiones de la plataforma Nokia AOR para Telefónica Chile, trabajando en entornos RHEL. Ejecución de pruebas IOT/UAT, troubleshooting, validación de parches y colaboración con equipos de ingeniería de Nokia España para resolver defectos. Desarrollo de scripts Bash para automatizar actividades de prueba.",
    experienceFiveDates: "Abr 2013 – Oct 2013", experienceFiveRole: "Desarrollador de Software (Freelance)", experienceFiveCompany: "SRB CORP S.A.", experienceFiveCopy: "Desarrollo de nuevas funcionalidades para un sistema ERP web de Sacyr Chile, participando en el levantamiento de requerimientos, diseño e implementación de soluciones con PHP, JavaScript, HTML, CSS y MySQL. Ejecución de pruebas funcionales, generación de reportes en Excel y elaboración de documentación técnica para la entrega al cliente.",
    experienceSixDates: "Mar 2011 – Abr 2013", experienceSixRole: "Desarrollador de Software", experienceSixCompany: "SIGTEC LTDA.", experienceSixCopy: "Desarrollo y mantenimiento del ERP web AITUE para clientes de distintas industrias, participando en el análisis de requerimientos, diseño e implementación de funcionalidades con PHP, JavaScript, HTML, CSS y MySQL. Modificación de bases de datos, resolución de defectos, pruebas funcionales, soporte a clientes y elaboración de documentación técnica.",
    projectsLabel: "Proyectos", projectsTitle: "Lo que estoy construyendo", projectOneTitle: "Infraestructura del portafolio personal", projectOneCopy: "Un portafolio alojado en Amazon EC2 con DNS en Route 53, Nginx, una Elastic IP y administración segura mediante AWS Systems Manager Session Manager.", viewRepository: "Ver en GitHub", projectTwoTitle: "Este sitio web de portafolio", projectTwoCopy: "Un sitio personal responsivo y accesible, creado con HTML semántico, CSS moderno y JavaScript ligero, sin frameworks.", nextProject: "Próximo proyecto", nextProjectCopy: "Este espacio está listo para el próximo desafío, experimento o herramienta útil que construya.", comingSoon: "Próximamente",
    skillsLabel: "Habilidades", skillsTitle: "Herramientas y tecnologías", cloud: "Servicios de AWS", cloudList: "Amazon EC2, Route 53, Systems Manager, IAM, Elastic IP", systems: "Sistemas e infraestructura", systemsList: "Linux (RHEL), Nginx, SSH, DNS, TLS/HTTPS, VMware, Cisco UCS", development: "Desarrollo y automatización", developmentList: "HTML, CSS, JavaScript, PHP, MySQL, Bash, Git, GitHub", practices: "Operaciones y prácticas", practicesList: "Monitoreo, resolución de problemas, despliegues, parchado, documentación, fundamentos de seguridad",
    hobbiesLabel: "Fuera del trabajo", hobbiesTitle: "Pasatiempos e intereses", hobbiesCopy: "Fuera del trabajo, disfruto de las cosas simples que me ayudan a mantener el equilibrio: pasar tiempo con mi hijo y mi pareja, viajar y conocer nuevos lugares, hacer deporte y jugar fútbol. También disfruto de una buena película, la lectura y dedicar tiempo a una de mis aficiones más creativas: dibujar mi propio manga.", technology: "Tecnología", continuousLearning: "Aprendizaje continuo", personalProjects: "Proyectos personales", familyTime: "Tiempo en familia", travel: "Viajar", sportsAndFootball: "Deporte y fútbol", movies: "Películas", reading: "Lectura", drawingManga: "Dibujar manga", builtBy: "Diseñado y construido por Boris Ramirez.", rights: "Todos los derechos reservados."
  }
};

function setLanguage(language) {
  const selected = translations[language] ? language : "en";
  const text = translations[selected];

  document.documentElement.lang = selected;
  document.title = text.pageTitle;
  document.querySelector('meta[name="description"]').content = text.description;
  document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = text[element.dataset.i18n]; });
  document.querySelectorAll("[data-i18n-aria-label]").forEach((element) => { element.setAttribute("aria-label", text[element.dataset.i18nAriaLabel]); });
  document.querySelectorAll("[data-i18n-alt]").forEach((element) => { element.alt = text[element.dataset.i18nAlt]; });
  languageButtons.forEach((button) => {
    const isActive = button.dataset.language === selected;
    button.classList.toggle("is-active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });
  localStorage.setItem("portfolio-language", selected);
}

year.textContent = new Date().getFullYear();

menuButton.addEventListener("click", () => {
  const isOpen = navigation.classList.toggle("is-open");
  menuButton.setAttribute("aria-expanded", String(isOpen));
});

navigationLinks.forEach((link) => {
  link.addEventListener("click", () => {
    navigation.classList.remove("is-open");
    menuButton.setAttribute("aria-expanded", "false");
  });
});

languageButtons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.language));
});

setLanguage(localStorage.getItem("portfolio-language") || "en");
